apiVersion: v1
kind: Service
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  - name: http-admin
    port: 9901
    targetPort: http
    protocol: TCP
  selector:
    app: envoy
