apiVersion: v1
kind: Service
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: envoy-admin
    port: 9901
    targetPort: 9901
    protocol: TCP
  selector:
    app: envoy
